node_js:
- '9'
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
    - muizudeen+npmjs@travis-ci.com
deploy:
  provider: npm
  email: muizudeen+npmjs@travis-ci.com
  api_key:
    secure: PvdI/UnDqPiZxGK2LIlbwvQ3NG0ECg5tsXu5KAsPyhyF4w8R1yONONgoc4/k5o1oZUL+5u+mG+9S+bfu+6GRwkopj24UU4hpddqSHiVMql0jB6ZNIqkCu0obEkvlQX0eqco1u/A7zWIYXhyUCcQwRMKCgtoMbF7If5ie1D7mQ4g1pZtDBb6aHDS9F0TsdXpCuHr+p8wZz6b87ESw/RCgPRFDQAIt13RL1YtSbMhksJfo545csMI2pb7x95XmYyDja9q4ifsnrD4miejfJcNMnwZ4+YZUFjZR11mGc2L8z0NrJ/Vvlb+T4zeI9eVS1ZRT5NY2zM2ZFOn3J8u5fPYosDnQOCMLGSG/4dM5hi4M/G16x1h3sR/PoIPi+1HFSvn8RBx3krylfC52L/aeLN6Zcjj3PRTaW9XowUSxEpvlbwE1ppGf2+Sd7SEW+QKY1aBcwBHIbsnPkdaJM8BTLjobvBiA2VtomHQvGJRN8UzBMn0TZA+KovJ75mLZRRfTKAbPZRlfE4b9KTQl0JSYc7sRJogFVzMRiG20KPLjjgZCA/utzCSNTWX3Pvf1NPy+nWpSTqjG35A0tlsUypLLACe5MPyIjW+ELBw3ttNbqHNGVnnK9aF8BlEbCOGHXrAWE1q8Ky5IvyvkvfkQWkKylDVQ5CkicrHkfw9tpIM27vUJK64=
  on:
    branch: master
